// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/6/2026, 4:02:10 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/hvekriya/Documents/git/Bhaktiras/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/Bhaktiras/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/Bhaktiras/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/Bhaktiras/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/Bhaktiras/plugins/**/*.{js,ts,mjs}","/Users/hvekriya/Documents/git/Bhaktiras/composables/**/*.{js,ts,mjs}","/Users/hvekriya/Documents/git/Bhaktiras/utils/**/*.{js,ts,mjs}","/Users/hvekriya/Documents/git/Bhaktiras/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/Bhaktiras/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/Bhaktiras/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/Bhaktiras/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;