import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

function loadEnvFile(rootDir) {
  try {
    const text = readFileSync(resolve(rootDir, '.env'), 'utf8')
    for (const line of text.split('\n')) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) continue
      const eq = trimmed.indexOf('=')
      if (eq <= 0) continue
      const key = trimmed.slice(0, eq).trim()
      const value = trimmed.slice(eq + 1).trim()
      if (!(key in process.env)) process.env[key] = value
    }
  } catch {
    // .env is optional when CI already injected the variables.
  }
}

/** Writes public/firebase-messaging-sw.js with the current Firebase web config. */
export function writeFirebaseMessagingSw(rootDir = process.cwd()) {
  loadEnvFile(rootDir)
  const projectId = process.env.NUXT_PUBLIC_FIREBASE_PROJECT_ID || ''
  const config = {
    apiKey: process.env.NUXT_PUBLIC_FIREBASE_API_KEY || '',
    authDomain: process.env.NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN || (projectId ? `${projectId}.firebaseapp.com` : ''),
    projectId,
    storageBucket: process.env.NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET || (projectId ? `${projectId}.firebasestorage.app` : ''),
    messagingSenderId: process.env.NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '',
    appId: process.env.NUXT_PUBLIC_FIREBASE_APP_ID || ''
  }

  const source = `/* Generated by scripts/writeFirebaseMessagingSw.mjs — do not edit by hand. */
importScripts('https://www.gstatic.com/firebasejs/11.0.2/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/11.0.2/firebase-messaging-compat.js')

firebase.initializeApp(${JSON.stringify(config, null, 2)})

const messaging = firebase.messaging()

function absoluteUrl(path) {
  try {
    return new URL(path || '/', self.location.origin).href
  } catch {
    return self.location.origin + '/'
  }
}

messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {}
  const notification = payload.notification || {}
  const title = notification.title || data.title || 'Bhaktiras'
  const options = {
    body: notification.body || data.body || '',
    icon: '/notification-icon.png',
    badge: '/notification-badge.png',
    data: { url: absoluteUrl(data.url) },
    tag: data.tag || 'bhaktiras-update',
    renotify: true
  }
  return self.registration.showNotification(title, options)
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const target = absoluteUrl(event.notification.data?.url || '/')
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      const existing = clients.find((client) => typeof client.focus === 'function')
      if (existing) {
        existing.navigate?.(target)
        return existing.focus()
      }
      return self.clients.openWindow(target)
    })
  )
})
`

  writeFileSync(resolve(rootDir, 'public/firebase-messaging-sw.js'), source)
}
