import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

function loadEnvFile(rootDir) {
  try {
    const text = readFileSync(resolve(rootDir, '.env'), 'utf8')
    for (const line of text.split('\n')) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) continue
      const eq = trimmed.indexOf('=')
      if (eq <= 0) continue
      const key = trimmed.slice(0, eq).trim()
      const value = trimmed.slice(eq + 1).trim()
      if (!(key in process.env)) process.env[key] = value
    }
  } catch {
    // .env is optional when CI already injected the variables.
  }
}

/** Writes public/firebase-messaging-sw.js with the current Firebase web config. */
export function writeFirebaseMessagingSw(rootDir = process.cwd()) {
  loadEnvFile(rootDir)
  const projectId = process.env.NUXT_PUBLIC_FIREBASE_PROJECT_ID || ''
  const config = {
    apiKey: process.env.NUXT_PUBLIC_FIREBASE_API_KEY || '',
    authDomain: process.env.NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN || (projectId ? `${projectId}.firebaseapp.com` : ''),
    projectId,
    storageBucket: process.env.NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET || (projectId ? `${projectId}.firebasestorage.app` : ''),
    messagingSenderId: process.env.NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '',
    appId: process.env.NUXT_PUBLIC_FIREBASE_APP_ID || ''
  }

  const source = `/* Generated by scripts/writeFirebaseMessagingSw.mjs — do not edit by hand. */
importScripts('https://www.gstatic.com/firebasejs/11.0.2/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/11.0.2/firebase-messaging-compat.js')

firebase.initializeApp(${JSON.stringify(config, null, 2)})

const messaging = firebase.messaging()

function absoluteUrl(path) {
  try {
    return new URL(path || '/', self.location.origin).href
  } catch {
    return self.location.origin + '/'
  }
}

messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {}
  const notification = payload.notification || {}
  const title = notification.title || data.title || 'Bhaktiras'
  const fullBody = notification.body || data.body || ''
  const preview = data.preview || fullBody
  const body = preview.length > 120 ? preview.slice(0, 119).trimEnd() + '…' : preview
  const options = {
    body,
    icon: '/notification-icon.png',
    badge: '/notification-badge.png',
    data: { url: absoluteUrl(data.url) },
    tag: data.tag || 'bhaktiras-update',
    renotify: true
  }
  return self.registration.showNotification(title, options)
})

/**
 * Chromium only offers "Install app" — and only fires \`beforeinstallprompt\` —
 * when a registered service worker has a fetch handler. Push needs a service
 * worker anyway, and two scripts cannot share the root scope (registering a
 * second one at '/' replaces this registration and silently kills push), so
 * installability rides along here. Requests pass straight through: Bhaktiras
 * has no offline story and this must not become an accidental cache layer.
 */
self.addEventListener('fetch', () => {})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const target = absoluteUrl(event.notification.data?.url || '/')
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      const existing = clients.find((client) => typeof client.focus === 'function')
      if (existing) {
        existing.navigate?.(target)
        return existing.focus()
      }
      return self.clients.openWindow(target)
    })
  )
})
`

  // A blank config produces a service worker that registers cleanly and can
  // never receive a push — no build error, nothing visibly wrong on the site.
  // So an incomplete config must never reach disk.
  //
  // The file is generated rather than committed (see .gitignore). It used to be
  // checked in, which meant any local build without .env rewrote it with empty
  // strings, and committing that shipped dead push to the whole sangat. Keeping
  // it out of git means the only copy that can reach production is the one CI
  // generates, and the throw below guarantees CI had real config to generate it
  // from.
  const missing = Object.entries(config).filter(([, value]) => !value).map(([key]) => key)
  if (missing.length) {
    const detail = `missing Firebase config (${missing.join(', ')}); `
      + 'populate .env or the NUXT_PUBLIC_FIREBASE_* environment variables'
    if (process.env.CI) {
      throw new Error(`Refusing to write public/firebase-messaging-sw.js: ${detail}.`)
    }
    console.warn(`[push] Skipped public/firebase-messaging-sw.js: ${detail}.`)
    return
  }

  writeFileSync(resolve(rootDir, 'public/firebase-messaging-sw.js'), source)
}
